# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 80
spring:
    profiles:
      active: db
    mvc:
      static-path-pattern: /static/**
    freemarker:
          suffix: .html
          request-context-attribute: request
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss