# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8002
spring:
    mvc:
      static-path-pattern: /static/**
    freemarker:
          suffix: .html
          request-context-attribute: request
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
  # 集群配置
    redis:
      expireSeconds: 60
      timeout: 5000ms  #redis操作的超时时间
      database: 0
      host: 192.168.254.201
      port: 6379